apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8081      # service port
      targetPort: 8080 # container port
  type: ClusterIP
